version: '3.8'

services:
  app:
    build:
      context: .
      target: final  
    ports:
      - "5000:80" 

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
